name: drinks_flutter_before
description: Replika Drinks Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  
  # Http client for Dart.
  dio: ^3.0.3

  # Reactive functional programming library for Google Dart, based on ReactiveX.
  rxdart: ^0.22.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/